Unittest to pytest
iver56/audiomentations pull request #193
Opened 2022-05-19 08:32 UTC by atamazian

Implements https://github.com/iver56/audiomentations/issues/176, except from `unittest.mock` in `test_room_simulator.py`. I can replace it with `pytest-mock` if necessary.

2022-05-19 08:35 UTC, atamazian commented
Can you ignore first two commits? They're related to https://github.com/iver56/audiomentations/pull/192 , and by mistake I included them here.

2022-05-20 07:10 UTC, iver56 commented
Could you somehow rebase out those commits from this branch? It would make it easier to get in this PR

2022-05-20 10:15 UTC, atamazian commented
Done! Can you review this now?

2022-05-20 11:57 UTC, iver56 commented
I tried to run the test suite, but it couldn't start due to:

```
___________________________________________________________ ERROR collecting tests/test_utils.py ___________________________________________________________
ImportError while importing test module 'C:\Users\iver5\Code\audiomentations\tests\test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_utils.py:4: in <module>
    from audiomentations.core.utils import (
E   ImportError: cannot import name 'find_audio_files_in_paths' from 'audiomentations.core.utils' (C:\Users\iver5\Code\audiomentations\audiomentations\core\utils.py)
```

2022-05-20 12:06 UTC, atamazian commented
Fixed. Can you check it now?

2022-05-20 12:35 UTC, iver56 requested changes
Looks good to me, except this small error (the test fails)

2022-05-20 12:35 UTC, iver56 commented on tests/test_gaussian_snr.py
> +        assert float(np.sum(np.abs(samples_out))) > float(np.sum(np.abs(samples_out)))
```suggestion
        assert float(np.sum(np.abs(samples_out))) > float(np.sum(np.abs(samples)))
```

2022-05-20 13:03 UTC, atamazian commented
Should I leave `unittest.mock` in `test_room_simulator.py`? Or it's better to replace it with something else?

2022-05-20 13:34 UTC, iver56 commented
> Should I leave `unittest.mock` in `test_room_simulator.py`? Or it's better to replace it with something else?

You can leave it as it is for now 👍

2022-05-20 13:37 UTC, iver56 approved these changes

2022-05-20 13:37 UTC, iver56 commented
Thanks for the contribution!

2022-05-20 13:37 UTC, merged