[Draft] Documentations
iver56/audiomentations pull request #236
Opened 2022-09-27 13:57 UTC by Thanatoz-1

[Draft]

This MR adds docs and their respective web objects in descending order.  
Docs completed so far are: 
- [x] Trim
- [ ] Time stretch
- [ ] Time Mask
- [ ] Tanh Distortion
- [ ] Shift
- [ ] Seven band parametric eq
- [ ] Room simulator
- [ ] Reverse
- [ ] Resample
- [ ] Polarity inversion
- [ ] Pitch Shift
- [ ] Peaking filter
- [ ] Padding
- [ ] Normalize
- [ ] mp3 compression
- [ ] Low shelf filter 
- [ ] Low pass filter 
- [ ] Loudness normalization
- [ ] Limiter
- [ ] Lambda
- [ ] High shelf filter
- [ ] High pass filter
- [ ] Gain
- [ ] Gain transition
- [ ] Clipping distortion
- [ ] Clip
- [ ] Band stop filter 
- [ ] Band pass filter
- [ ] Apply impulse response
- [ ] Air absoption
- [ ] Add short noises
- [x] Add gaussian SNR
- [x] Add gaussian noise
- [x] Add background noise

2022-09-27 14:03 UTC, Thanatoz-1 commented
Hey @iver56 ,
I am pushing my first documentation [Trim] here. I am considering a document to be complete only if it contains the waveform & spectrogram comparison, and audio samples. Please correct me wherever I might be wrong or else I will continue.

2022-09-27 14:10 UTC, iver56 requested changes
Thanks :) Can you also include your changes in generate_examples_for_doc.py?

2022-09-27 14:10 UTC, iver56 commented on docs/waveform_transforms/trim.md
> +[`top_db`](#top_db){ #top_db }: `float`
```suggestion
[`top_db`](#top_db){ #top_db }: `float` • unit: Decibel
```

2022-09-27 14:10 UTC, iver56 commented on docs/waveform_transforms/trim.md
> +## Usage examples
```suggestion
## Usage example
```

2022-09-27 14:15 UTC, Thanatoz-1 commented
Certainly, I'll also add changes in the generate_examples_for_doc.py

2022-09-27 14:21 UTC, iver56 commented
I just merged some of my own documentation updates btw: https://github.com/iver56/audiomentations/pull/237

2022-09-27 14:22 UTC, Thanatoz-1 commented
Thanks, Taking a pull now and updating the MR too.

2022-10-05 08:10 UTC, iver56 commented
I will wait for your changes in generate_examples_for_doc.py, and then I think this is ready to be merged

2022-10-05 08:13 UTC, iver56 commented
One thing I'm not sure if I like is the dependency on AddGaussianNoise_input.flac

There are pros and cons

Pro:

* We save space in the repository and maybe save some network bandwidth for uses that browse several documentation pages (because cache)

Con:

* Maintenance becomes harder. For example, if I update the audio example in the AddGaussianNoise documentation, other pages that rely on AddGaussianNoise_input.flac will be broken

What do you think? Does the pro outweight the con?

2022-10-05 18:18 UTC, Thanatoz-1 commented
Hey @iver56,

Sorry for not being able to reply sooner. I tried to think over this trade-off and for now, I feel let's try to avoid cons and stick to two separate files for each transform (input and output).  I've modified the `generate_examples_for_docs.py` and have added most of the transforms for now. I'll push all the changes in some time and then you can merge.

2022-10-06 07:10 UTC, iver56 approved these changes

2022-10-06 07:10 UTC, iver56 commented
Thanks 👍

2022-10-06 07:10 UTC, merged

2022-10-06 09:13 UTC, Thanatoz-1 commented
Also, for the remaining documents, I will be creating another MR and update the rest of it asap.