Feature/24 bit support
iver56/audiomentations pull request #93
Opened 2021-03-08 11:26 UTC by fmirus

Now also add 24-bit support making use of both scipy.io and wavio read functions. This is able to read almost all wav files. I still get some errors with 24-bit files with very high sampling rates (order of magnitude 44k), which seems to be a limitation in the wavio/wave read functions themselves.

2021-03-08 11:52 UTC, iver56 commented
* I would really like to have some tests for this. It would be nice to have some small test fixture files with various formats.
* There is a function called `load_wav_file_with_wavio`. What should we do with it? Having duplicated code feels suboptimal
* I think the newest scipy loads 24-bit wavs with `samples.dtype == np.int32`, so it would go into the same part of the code as the int32 files, where we divide by 2147483648. How should we handle that?

2021-03-08 11:55 UTC, iver56 requested changes

2021-03-08 11:55 UTC, iver56 commented on audiomentations/core/audio_loading_utils.py
> +    except:
Too broad exception handler. What kind of exception are we expecting here?

2021-03-08 11:55 UTC, iver56 commented on audiomentations/core/audio_loading_utils.py
> +        except:
Too broad exception handler. For example, if the file no longer exists or cannot be read for some reason, we don't want to say "unexpected data type"

2021-03-08 11:57 UTC, iver56 commented
> I still get some errors with 24-bit files with very high sampling rates

Those would be interesting to have as test cases, if it is feasible to add them as small test fixture files

2021-03-12 10:08 UTC, fmirus commented
@iver56 Those are really good remarks. I was not aware, that the newest scipy supports all wav formats and thus basically solves this issue. Therefore, I withdraw this PR.

2021-03-12 10:08 UTC, closed without merging

2021-03-12 10:21 UTC, iver56 commented
Ok. I'll have a look myself to see how these issues can be fixed in a good way.
Thanks for the effort though.